### ISSUE TITLE
Duvidas sobre categorias

### ISSUE THREAD

**Issue by andersonweb** [nandomoreirame/nandomoreirame.github.io#3]
Olá Nando, tudo bem ?
Cara... estou desenvolvendo um site em Jekyll e fiquei frustado e querendo entender como funciona esse lance das categorias e como você implementou, poderia "explicar" ?

Vi que você criou uma pasta com o nome categories e vários arquivos com o nome das categorias.  Até ai ok. A minha maior duvida é como você chama os posts para cada página.

Grato desde já, parabéns, o site ficou muito bacana.

**Comment by nandomoreirame** [comment]
Dae @andersonweb de boa brother?!
Seguinte, eu segui esse [tutorial aqui](http://www.minddust.com/post/tags-and-categories-on-github-pages/) do Stephan, muito bom.
Se precisar de uma ajuda pra implementar eu te dou um help dando um fork no seu repo ai :+1: 
Eu vou traduzir esse post do Stephan em breve, pra ajudar quem precisar aqui do Brasil.
